In [1]:
!rm -rf ./logs/ 
%run Model.ipynb
%run dataset_loader.ipynb
import tensorflow as tf
import numpy
import sys
#from dataset_loader import load_dataset

test_no = 58

#tf.enable_eager_execution()
INPUT_WIDTH = 64
INPUT_HEIGHT = 64

INPUT_SIZE = 64

INPUT_CHANNELS = 1

NUM_CLASSES = 5

LEARNING_RATE = 0.0001  # Original value: 0.01
# DECAY_POINT = 2000
DECAY_RATE = 10



DROPOUT_RATE = 0

EPOCHS = 12000
GLOBAL_STEPS = 100
BATCH_SIZE = 256

NUM_PARRALLEL_THREADS = 10

GRAYSCALE=True
IS_FREQUENCY = False

RESTORE = True

train_sub_dir = '/data/image_format/training_data_15000/*/*'
val_sub_dir = '/data/image_format/validation_data/*/*'
test_sub_dir = '/data/image_format/test_data/*/*'

frequency_train_sub_dir = '/data/cogisen_frequency_data/training_data_15000_cogisen/*/*/*.csv'
frequency_val_sub_dir = '/data/cogisen_frequency_data/validation_data_1500_cogisen/*/*/*.csv'
frequency_test_sub_dir = '/data/cogisen_frequency_data/test_data_1500_cogisen/*/*/*.csv'



# train_sub_dir = '/data/image_format/small_dataset/train/*/*'
# val_sub_dir = '/data/image_format/small_dataset/val/*/*'
# test_sub_dir = '/data/image_format/small_dataset/test/*/*'

# frequency_train_sub_dir = '/data/cogisen_frequency_data/small_dataset/train/*/*/*.csv'
# frequency_val_sub_dir = '/data/cogisen_frequency_data/small_dataset/val/*/*/*.csv'
# frequency_test_sub_dir = '/data/cogisen_frequency_data/small_dataset/test/*/*/*.csv'






home_dir = os.path.dirname(os.path.realpath('__file__'))

train_dir = home_dir + train_sub_dir
val_dir = home_dir + val_sub_dir
test_dir = home_dir + test_sub_dir


frequency_train_dir = home_dir + frequency_train_sub_dir
frequency_val_dir = home_dir + frequency_val_sub_dir
frequency_test_dir = home_dir + frequency_test_sub_dir



training_dataset= load_dataset(img_dir= train_dir,frequency_dir=frequency_train_dir,minibatch_size=BATCH_SIZE,image_size=INPUT_SIZE,grayscale=GRAYSCALE,num_parallel_calls=NUM_PARRALLEL_THREADS,is_frequency=IS_FREQUENCY)

# logdir = './log/simple_model/frequency_data/grayscale'+str(experiment_no)
# weight_dir = './weights/simple_model/frequency_data/grayscale/'+str(experiment_no)+'/model'


logdir = home_dir+'/log/2_test/test/' + str(test_no)

weight_dir = home_dir+'/weights/test/' +str(test_no)

weights = weight_dir +'/model'
if not os.path.exists(weight_dir):
    os.makedirs(os.path.join(weight_dir))
    


/home/shubham/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/shubham/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/shubham/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/shubham/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:5

In [2]:
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'XLA_GPU']

In [3]:
get_available_gpus()

['/device:XLA_GPU:0']

In [4]:

handle = tf.placeholder(tf.string, shape=[],name="data_handle")

with tf.name_scope('iterators'):
    training_iterator = tf.data.Iterator.from_structure(training_dataset.output_types,training_dataset.output_shapes)
    training_init_op = training_iterator.make_initializer(training_dataset)
    

Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.


In [5]:
iterator = tf.data.Iterator.from_string_handle(
    handle, training_iterator.output_types,training_dataset.output_shapes)

next_training_element = iterator.get_next()



In [6]:
#with tf.device('/device:XLA_GPU:0'):
model = Simple_Model(next_training_element,input_height=INPUT_HEIGHT,input_width=INPUT_WIDTH, num_classes=NUM_CLASSES,input_channels=INPUT_CHANNELS,dropout_rate=DROPOUT_RATE,learning_rate=LEARNING_RATE)


[None, 3, 3, 16]


In [7]:

#train_sub_dir = '/data/image_format/training_data_1500/*/*'
val_dataset = load_dataset(img_dir= val_dir,frequency_dir=frequency_val_dir,minibatch_size=1500,image_size=INPUT_SIZE,grayscale=GRAYSCALE,num_parallel_calls=NUM_PARRALLEL_THREADS,is_frequency=IS_FREQUENCY)

val_iterator = tf.data.Iterator.from_structure(val_dataset.output_types,val_dataset.output_shapes)
val_init_op = val_iterator.make_initializer(val_dataset,name='val_init_op')
 

In [ ]:

# if RESTORE:
#     tf.reset_default_graph()
#     graph = tf.get_default_graph()
#     saver = tf.train.import_meta_graph(meta_dir)




with tf.device('/device:XLA_GPU:0'):

    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:
        
        sess.run(tf.global_variables_initializer())
        
     
        file_writer = tf.summary.FileWriter(logdir=logdir, graph=sess.graph)

        
        summary_operation = tf.summary.merge_all()
        
        saver = tf.train.Saver()
        saver.save(sess, weights)
        training_string_handle =  sess.run(training_iterator.string_handle())
        val_handle = sess.run(val_iterator.string_handle())
        numpy.set_printoptions(threshold=sys.maxsize)
        
        # Original value: 0.01
        for epoch in range(EPOCHS):
            
            sess.run(training_init_op,feed_dict={handle:training_string_handle})
            saver.save(sess, weights,global_step=GLOBAL_STEPS,write_meta_graph=False)
            
#             if epoch == DECAY_POINT:
#                 LEARNING_RATE = LEARNING_RATE/DECAY_RATE
                
            while True:
                
                try:
                    _, train_accuracy,summary,input_image,predictions= sess.run([model.training_operation,model.accuracy_operation,summary_operation,model.X,model.predictions],feed_dict={handle:training_string_handle,model.learning_rate:LEARNING_RATE})
            
                except tf.errors.OutOfRangeError:
                    
                    file_writer.add_summary(summary, epoch)
                    
                    if epoch%5 ==0:
                        print("accuracy for training set for epoch {0} is  :  {1}".format(epoch,train_accuracy))
                        #print("input_image = ",input_image[0][0])
                        print("predictions: ",predictions[:5])
           
                    break
            
            
            
            
            if epoch%5 ==0:
                sess.run(val_init_op,feed_dict={handle:val_handle})
            

                while True:
                    try:

                        val_accuracy,loss = sess.run([model.accuracy_operation,model.loss],feed_dict={handle:val_handle})
                        
                    except tf.errors.OutOfRangeError:
                        
                        print("accuracy for validation set for epoch {0} is  :  {1} and loss is {2}".format(epoch,val_accuracy,loss))

                        break


                
                


            
            

                
            
           





accuracy for training set for epoch 0 is  :  0.19078947603702545
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 0 is  :  0.2006666660308838 and loss is 5469652662616064.0
accuracy for training set for epoch 5 is  :  0.20394736528396606
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 5 is  :  0.17466667294502258 and loss is 873599904776192.0
accuracy for training set for epoch 10 is  :  0.2763157784938812
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 10 is  :  0.24199999868869781 and loss is 446991742009344.0
accuracy for training set for epoch 15 is  :  0.31578946113586426
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set

accuracy for validation set for epoch 150 is  :  0.218666672706604 and loss is 61799139377152.0
accuracy for training set for epoch 155 is  :  0.25
predictions:  [[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 155 is  :  0.21666666865348816 and loss is 60525018873856.0
accuracy for training set for epoch 160 is  :  0.19736842811107635
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 160 is  :  0.2160000056028366 and loss is 59231310970880.0
accuracy for training set for epoch 165 is  :  0.30263158679008484
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 165 is  :  0.21266666054725647 and loss is 58138325680128.0
accuracy for training set for epoch 170 is  :  0.23026315867900848
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 

accuracy for validation set for epoch 305 is  :  0.23066666722297668 and loss is 26703615229952.0
accuracy for training set for epoch 310 is  :  0.25
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 310 is  :  0.2266666740179062 and loss is 26289979260928.0
accuracy for training set for epoch 315 is  :  0.28289473056793213
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 315 is  :  0.22200000286102295 and loss is 25986796093440.0
accuracy for training set for epoch 320 is  :  0.25
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 320 is  :  0.22333332896232605 and loss is 25415921958912.0
accuracy for training set for epoch 325 is  :  0.25
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0

accuracy for validation set for epoch 460 is  :  0.20999999344348907 and loss is 18667609784320.0
accuracy for training set for epoch 465 is  :  0.21710526943206787
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 465 is  :  0.20666666328907013 and loss is 18527805243392.0
accuracy for training set for epoch 470 is  :  0.29605263471603394
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 470 is  :  0.21066667139530182 and loss is 18433114636288.0
accuracy for training set for epoch 475 is  :  0.25
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 475 is  :  0.24400000274181366 and loss is 18293062631424.0
accuracy for training set for epoch 480 is  :  0.23026315867900848
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 

accuracy for validation set for epoch 615 is  :  0.23466666042804718 and loss is 14903512399872.0
accuracy for training set for epoch 620 is  :  0.29605263471603394
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 620 is  :  0.24199999868869781 and loss is 14808640389120.0
accuracy for training set for epoch 625 is  :  0.2631579041481018
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 625 is  :  0.23933333158493042 and loss is 14704765304832.0
accuracy for training set for epoch 630 is  :  0.34210526943206787
predictions:  [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 630 is  :  0.23733332753181458 and loss is 14583095885824.0
accuracy for training set for epoch 635 is  :  0.25
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1

accuracy for validation set for epoch 770 is  :  0.23399999737739563 and loss is 12551998930944.0
accuracy for training set for epoch 775 is  :  0.29605263471603394
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 775 is  :  0.22066666185855865 and loss is 12516130291712.0
accuracy for training set for epoch 780 is  :  0.23026315867900848
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 780 is  :  0.22599999606609344 and loss is 12423660568576.0
accuracy for training set for epoch 785 is  :  0.16447368264198303
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 785 is  :  0.22333332896232605 and loss is 12407759962112.0
accuracy for training set for epoch 790 is  :  0.2763157784938812
predictions:  [[0. 1. 0. 0

accuracy for validation set for epoch 925 is  :  0.23733332753181458 and loss is 10903310303232.0
accuracy for training set for epoch 930 is  :  0.2565789520740509
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 930 is  :  0.25 and loss is 10902713663488.0
accuracy for training set for epoch 935 is  :  0.33552631735801697
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 935 is  :  0.24133333563804626 and loss is 10839205609472.0
accuracy for training set for epoch 940 is  :  0.2631579041481018
predictions:  [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 940 is  :  0.24133333563804626 and loss is 10759151026176.0
accuracy for training set for epoch 945 is  :  0.2434210479259491
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 

accuracy for validation set for epoch 1080 is  :  0.21666666865348816 and loss is 9667571875840.0
accuracy for training set for epoch 1085 is  :  0.21710526943206787
predictions:  [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 1085 is  :  0.23999999463558197 and loss is 9620825309184.0
accuracy for training set for epoch 1090 is  :  0.29605263471603394
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 1090 is  :  0.23600000143051147 and loss is 9573599543296.0
accuracy for training set for epoch 1095 is  :  0.23026315867900848
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 1095 is  :  0.22066666185855865 and loss is 9539943399424.0
accuracy for training set for epoch 1100 is  :  0.2434210479259491
predictions:  [[0. 0. 

accuracy for training set for epoch 1235 is  :  0.31578946113586426
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 1235 is  :  0.23933333158493042 and loss is 8659256999936.0
accuracy for training set for epoch 1240 is  :  0.2565789520740509
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 1240 is  :  0.2433333396911621 and loss is 8617134653440.0
accuracy for training set for epoch 1245 is  :  0.28289473056793213
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 1245 is  :  0.24533332884311676 and loss is 8601293815808.0
accuracy for training set for epoch 1250 is  :  0.2697368562221527
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for vali

accuracy for validation set for epoch 1385 is  :  0.2173333317041397 and loss is 7879304151040.0
accuracy for training set for epoch 1390 is  :  0.28289473056793213
predictions:  [[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 1390 is  :  0.24799999594688416 and loss is 7820273516544.0
accuracy for training set for epoch 1395 is  :  0.30263158679008484
predictions:  [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 1395 is  :  0.2433333396911621 and loss is 7796819492864.0
accuracy for training set for epoch 1400 is  :  0.2565789520740509
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 1400 is  :  0.23733332753181458 and loss is 7775384502272.0
accuracy for training set for epoch 1405 is  :  0.3552631437778473
predictions:  [[0. 0. 0. 

accuracy for validation set for epoch 1540 is  :  0.25200000405311584 and loss is 7156065632256.0
accuracy for training set for epoch 1545 is  :  0.32894736528396606
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 1545 is  :  0.2473333328962326 and loss is 7144011202560.0
accuracy for training set for epoch 1550 is  :  0.2697368562221527
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 1550 is  :  0.24066667258739471 and loss is 7103455952896.0
accuracy for training set for epoch 1555 is  :  0.25
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 1555 is  :  0.2473333328962326 and loss is 7076341350400.0
accuracy for training set for epoch 1560 is  :  0.28289473056793213
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0.

accuracy for validation set for epoch 1695 is  :  0.24199999868869781 and loss is 6530141257728.0
accuracy for training set for epoch 1700 is  :  0.30921053886413574
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 1700 is  :  0.23933333158493042 and loss is 6518769451008.0
accuracy for training set for epoch 1705 is  :  0.32894736528396606
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 1705 is  :  0.2486666738986969 and loss is 6502362382336.0
accuracy for training set for epoch 1710 is  :  0.29605263471603394
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 1710 is  :  0.24400000274181366 and loss is 6472494219264.0
accuracy for training set for epoch 1715 is  :  0.3947368562221527
predictions:  [[0. 0. 0

accuracy for training set for epoch 1850 is  :  0.22368420660495758
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 1850 is  :  0.2253333330154419 and loss is 6009176195072.0
accuracy for training set for epoch 1855 is  :  0.31578946113586426
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 1855 is  :  0.24199999868869781 and loss is 5981492740096.0
accuracy for training set for epoch 1860 is  :  0.25
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 1860 is  :  0.22733333706855774 and loss is 6010255704064.0
accuracy for training set for epoch 1865 is  :  0.2697368562221527
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for

accuracy for validation set for epoch 2000 is  :  0.23733332753181458 and loss is 5553093345280.0
accuracy for training set for epoch 2005 is  :  0.3684210479259491
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2005 is  :  0.23933333158493042 and loss is 5545817276416.0
accuracy for training set for epoch 2010 is  :  0.3552631437778473
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2010 is  :  0.23866666853427887 and loss is 5524646526976.0
accuracy for training set for epoch 2015 is  :  0.2631579041481018
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2015 is  :  0.23999999463558197 and loss is 5512929214464.0
accuracy for training set for epoch 2020 is  :  0.25
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1.

accuracy for training set for epoch 2155 is  :  0.3552631437778473
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 2155 is  :  0.23933333158493042 and loss is 5157047238656.0
accuracy for training set for epoch 2160 is  :  0.30263158679008484
predictions:  [[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 2160 is  :  0.2213333398103714 and loss is 5145193086976.0
accuracy for training set for epoch 2165 is  :  0.3486842215061188
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 2165 is  :  0.23533333837985992 and loss is 5118824546304.0
accuracy for training set for epoch 2170 is  :  0.30921053886413574
predictions:  [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for vali

accuracy for validation set for epoch 2305 is  :  0.23999999463558197 and loss is 4763299086336.0
accuracy for training set for epoch 2310 is  :  0.3486842215061188
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 2310 is  :  0.23266667127609253 and loss is 4765980819456.0
accuracy for training set for epoch 2315 is  :  0.3486842215061188
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2315 is  :  0.23066666722297668 and loss is 4757943484416.0
accuracy for training set for epoch 2320 is  :  0.34210526943206787
predictions:  [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 2320 is  :  0.23066666722297668 and loss is 4734974427136.0
accuracy for training set for epoch 2325 is  :  0.28289473056793213
predictions:  [[0. 0. 0

accuracy for training set for epoch 2460 is  :  0.28947368264198303
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 2460 is  :  0.23333333432674408 and loss is 4429950484480.0
accuracy for training set for epoch 2465 is  :  0.3947368562221527
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2465 is  :  0.24066667258739471 and loss is 4416924549120.0
accuracy for training set for epoch 2470 is  :  0.2697368562221527
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2470 is  :  0.23466666042804718 and loss is 4409557254144.0
accuracy for training set for epoch 2475 is  :  0.2434210479259491
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
accuracy for vali

accuracy for validation set for epoch 2610 is  :  0.22466666996479034 and loss is 4147447595008.0
accuracy for training set for epoch 2615 is  :  0.30921053886413574
predictions:  [[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2615 is  :  0.2213333398103714 and loss is 4147381010432.0
accuracy for training set for epoch 2620 is  :  0.28947368264198303
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2620 is  :  0.23866666853427887 and loss is 4123229683712.0
accuracy for training set for epoch 2625 is  :  0.3486842215061188
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2625 is  :  0.23733332753181458 and loss is 4124275376128.0
accuracy for training set for epoch 2630 is  :  0.2763157784938812
predictions:  [[0. 0. 1.

accuracy for validation set for epoch 2765 is  :  0.23866666853427887 and loss is 3869780475904.0
accuracy for training set for epoch 2770 is  :  0.29605263471603394
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 2770 is  :  0.24066667258739471 and loss is 3861905145856.0
accuracy for training set for epoch 2775 is  :  0.29605263471603394
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 2775 is  :  0.2173333317041397 and loss is 3872044613632.0
accuracy for training set for epoch 2780 is  :  0.375
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 2780 is  :  0.23466666042804718 and loss is 3844200464384.0
accuracy for training set for epoch 2785 is  :  0.46710526943206787
predictions:  [[0. 1. 0. 0. 0.]
 [0.

accuracy for validation set for epoch 2920 is  :  0.23999999463558197 and loss is 3629171867648.0
accuracy for training set for epoch 2925 is  :  0.28289473056793213
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2925 is  :  0.23800000548362732 and loss is 3630592425984.0
accuracy for training set for epoch 2930 is  :  0.3947368562221527
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 2930 is  :  0.23533333837985992 and loss is 3620713005056.0
accuracy for training set for epoch 2935 is  :  0.375
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 2935 is  :  0.23733332753181458 and loss is 3611686600704.0
accuracy for training set for epoch 2940 is  :  0.31578946113586426
predictions:  [[0. 0. 1. 0. 0.]
 [0.

accuracy for validation set for epoch 3075 is  :  0.23333333432674408 and loss is 3431339917312.0
accuracy for training set for epoch 3080 is  :  0.2763157784938812
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 3080 is  :  0.23733332753181458 and loss is 3436509396992.0
accuracy for training set for epoch 3085 is  :  0.32894736528396606
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 3085 is  :  0.23666666448116302 and loss is 3423690555392.0
accuracy for training set for epoch 3090 is  :  0.33552631735801697
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 3090 is  :  0.23733332753181458 and loss is 3415989813248.0
accuracy for training set for epoch 3095 is  :  0.3618420958518982
predictions:  [[1. 0. 0

accuracy for validation set for epoch 3230 is  :  0.23199999332427979 and loss is 3261381738496.0
accuracy for training set for epoch 3235 is  :  0.3881579041481018
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3235 is  :  0.23266667127609253 and loss is 3247584051200.0
accuracy for training set for epoch 3240 is  :  0.30921053886413574
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3240 is  :  0.23666666448116302 and loss is 3261881909248.0
accuracy for training set for epoch 3245 is  :  0.3947368562221527
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3245 is  :  0.23000000417232513 and loss is 3251554746368.0
accuracy for training set for epoch 3250 is  :  0.29605263471603394
predictions:  [[0. 0. 0

accuracy for validation set for epoch 3385 is  :  0.23800000548362732 and loss is 3096689770496.0
accuracy for training set for epoch 3390 is  :  0.3881579041481018
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 3390 is  :  0.21799999475479126 and loss is 3092450639872.0
accuracy for training set for epoch 3395 is  :  0.375
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 3395 is  :  0.21799999475479126 and loss is 3078955991040.0
accuracy for training set for epoch 3400 is  :  0.33552631735801697
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 3400 is  :  0.23533333837985992 and loss is 3072600309760.0
accuracy for training set for epoch 3405 is  :  0.33552631735801697
predictions:  [[0. 0. 1. 0. 0.]
 [0.

accuracy for validation set for epoch 3540 is  :  0.23466666042804718 and loss is 2939210170368.0
accuracy for training set for epoch 3545 is  :  0.3684210479259491
predictions:  [[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3545 is  :  0.23733332753181458 and loss is 2946004418560.0
accuracy for training set for epoch 3550 is  :  0.25
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3550 is  :  0.23399999737739563 and loss is 2925365297152.0
accuracy for training set for epoch 3555 is  :  0.31578946113586426
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 3555 is  :  0.21466666460037231 and loss is 2930417074176.0
accuracy for training set for epoch 3560 is  :  0.30921053886413574
predictions:  [[0. 0. 0. 1. 0.]
 [0. 

accuracy for validation set for epoch 3695 is  :  0.24533332884311676 and loss is 2817497235456.0
accuracy for training set for epoch 3700 is  :  0.3947368562221527
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 3700 is  :  0.24133333563804626 and loss is 2809975799808.0
accuracy for training set for epoch 3705 is  :  0.4013157784938812
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 3705 is  :  0.2486666738986969 and loss is 2803698761728.0
accuracy for training set for epoch 3710 is  :  0.30921053886413574
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 3710 is  :  0.23933333158493042 and loss is 2803294011392.0
accuracy for training set for epoch 3715 is  :  0.4013157784938812
predictions:  [[0. 0. 0. 

accuracy for validation set for epoch 3850 is  :  0.24933333694934845 and loss is 2701659209728.0
accuracy for training set for epoch 3855 is  :  0.3815789520740509
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 3855 is  :  0.24066667258739471 and loss is 2705951031296.0
accuracy for training set for epoch 3860 is  :  0.3486842215061188
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 3860 is  :  0.2433333396911621 and loss is 2694911098880.0
accuracy for training set for epoch 3865 is  :  0.3815789520740509
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 3865 is  :  0.2173333317041397 and loss is 2698489888768.0
accuracy for training set for epoch 3870 is  :  0.33552631735801697
predictions:  [[0. 1. 0. 0

accuracy for validation set for epoch 4005 is  :  0.24933333694934845 and loss is 2590650662912.0
accuracy for training set for epoch 4010 is  :  0.3815789520740509
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4010 is  :  0.24533332884311676 and loss is 2588673310720.0
accuracy for training set for epoch 4015 is  :  0.3684210479259491
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 4015 is  :  0.22466666996479034 and loss is 2587446476800.0
accuracy for training set for epoch 4020 is  :  0.3486842215061188
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4020 is  :  0.24199999868869781 and loss is 2579814678528.0
accuracy for training set for epoch 4025 is  :  0.3815789520740509
predictions:  [[0. 0. 0. 

accuracy for validation set for epoch 4160 is  :  0.2446666657924652 and loss is 2484970455040.0
accuracy for training set for epoch 4165 is  :  0.4013157784938812
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 4165 is  :  0.24133333563804626 and loss is 2484920909824.0
accuracy for training set for epoch 4170 is  :  0.3684210479259491
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 4170 is  :  0.25066667795181274 and loss is 2478183546880.0
accuracy for training set for epoch 4175 is  :  0.46052631735801697
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 4175 is  :  0.24799999594688416 and loss is 2476820398080.0
accuracy for training set for epoch 4180 is  :  0.31578946113586426
predictions:  [[0. 1. 0.

accuracy for validation set for epoch 4315 is  :  0.2486666738986969 and loss is 2396933324800.0
accuracy for training set for epoch 4320 is  :  0.375
predictions:  [[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 4320 is  :  0.2280000001192093 and loss is 2387455508480.0
accuracy for training set for epoch 4325 is  :  0.3552631437778473
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4325 is  :  0.2486666738986969 and loss is 2381723205632.0
accuracy for training set for epoch 4330 is  :  0.32894736528396606
predictions:  [[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 4330 is  :  0.24400000274181366 and loss is 2385784340480.0
accuracy for training set for epoch 4335 is  :  0.3947368562221527
predictions:  [[0. 0. 0. 0. 1.]
 [1. 0. 

accuracy for validation set for epoch 4470 is  :  0.25066667795181274 and loss is 2301095051264.0
accuracy for training set for epoch 4475 is  :  0.3815789520740509
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 4475 is  :  0.23266667127609253 and loss is 2298560118784.0
accuracy for training set for epoch 4480 is  :  0.3618420958518982
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 4480 is  :  0.2526666522026062 and loss is 2289062379520.0
accuracy for training set for epoch 4485 is  :  0.42105263471603394
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 4485 is  :  0.2513333261013031 and loss is 2288040804352.0
accuracy for training set for epoch 4490 is  :  0.3947368562221527
predictions:  [[0. 1. 0. 0

accuracy for validation set for epoch 4625 is  :  0.23266667127609253 and loss is 2205577904128.0
accuracy for training set for epoch 4630 is  :  0.4013157784938812
predictions:  [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 4630 is  :  0.25333333015441895 and loss is 2201678249984.0
accuracy for training set for epoch 4635 is  :  0.375
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 4635 is  :  0.25466665625572205 and loss is 2209174519808.0
accuracy for training set for epoch 4640 is  :  0.3684210479259491
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 4640 is  :  0.23199999332427979 and loss is 2204971040768.0
accuracy for training set for epoch 4645 is  :  0.34210526943206787
predictions:  [[0. 0. 0. 1. 0.]
 [0. 

accuracy for validation set for epoch 4780 is  :  0.2566666603088379 and loss is 2131425361920.0
accuracy for training set for epoch 4785 is  :  0.40789473056793213
predictions:  [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4785 is  :  0.24799999594688416 and loss is 2134549856256.0
accuracy for training set for epoch 4790 is  :  0.3684210479259491
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4790 is  :  0.25600001215934753 and loss is 2127800827904.0
accuracy for training set for epoch 4795 is  :  0.3552631437778473
predictions:  [[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 4795 is  :  0.23666666448116302 and loss is 2134910828544.0
accuracy for training set for epoch 4800 is  :  0.375
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0

accuracy for validation set for epoch 4935 is  :  0.2553333342075348 and loss is 2065890672640.0
accuracy for training set for epoch 4940 is  :  0.42105263471603394
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 4940 is  :  0.25600001215934753 and loss is 2064343498752.0
accuracy for training set for epoch 4945 is  :  0.4013157784938812
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 4945 is  :  0.2540000081062317 and loss is 2056043757568.0
accuracy for training set for epoch 4950 is  :  0.32894736528396606
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 4950 is  :  0.25466665625572205 and loss is 2052621729792.0
accuracy for training set for epoch 4955 is  :  0.40789473056793213
predictions:  [[0. 0. 1.

accuracy for validation set for epoch 5090 is  :  0.24666666984558105 and loss is 1995626905600.0
accuracy for training set for epoch 5095 is  :  0.3881579041481018
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 5095 is  :  0.2526666522026062 and loss is 1998846427136.0
accuracy for training set for epoch 5100 is  :  0.375
predictions:  [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 5100 is  :  0.2486666738986969 and loss is 1988952457216.0
accuracy for training set for epoch 5105 is  :  0.44736841320991516
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 5105 is  :  0.2473333328962326 and loss is 1986373353472.0
accuracy for training set for epoch 5110 is  :  0.4013157784938812
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 

accuracy for validation set for epoch 5245 is  :  0.2473333328962326 and loss is 1935415312384.0
accuracy for training set for epoch 5250 is  :  0.375
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 5250 is  :  0.23000000417232513 and loss is 1937260544000.0
accuracy for training set for epoch 5255 is  :  0.42763158679008484
predictions:  [[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 5255 is  :  0.2526666522026062 and loss is 1934075625472.0
accuracy for training set for epoch 5260 is  :  0.40789473056793213
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 5260 is  :  0.25 and loss is 1928988590080.0
accuracy for training set for epoch 5265 is  :  0.46052631735801697
predictions:  [[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [

accuracy for validation set for epoch 5400 is  :  0.24666666984558105 and loss is 1877229436928.0
accuracy for training set for epoch 5405 is  :  0.42105263471603394
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 5405 is  :  0.2266666740179062 and loss is 1875304644608.0
accuracy for training set for epoch 5410 is  :  0.43421053886413574
predictions:  [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 5410 is  :  0.2486666738986969 and loss is 1873502273536.0
accuracy for training set for epoch 5415 is  :  0.3486842215061188
predictions:  [[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
accuracy for validation set for epoch 5415 is  :  0.25066667795181274 and loss is 1875746619392.0
accuracy for training set for epoch 5420 is  :  0.44078946113586426
predictions:  [[0. 0. 1.

accuracy for validation set for epoch 5555 is  :  0.25 and loss is 1823725453312.0
accuracy for training set for epoch 5560 is  :  0.43421053886413574
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 5560 is  :  0.23399999737739563 and loss is 1830037487616.0
accuracy for training set for epoch 5565 is  :  0.3486842215061188
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 5565 is  :  0.23133333027362823 and loss is 1825585889280.0
accuracy for training set for epoch 5570 is  :  0.3881579041481018
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 5570 is  :  0.23333333432674408 and loss is 1823505121280.0
accuracy for training set for epoch 5575 is  :  0.375
predictions:  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [

accuracy for validation set for epoch 5710 is  :  0.2526666522026062 and loss is 1775085420544.0
accuracy for training set for epoch 5715 is  :  0.41447368264198303
predictions:  [[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 5715 is  :  0.25200000405311584 and loss is 1769867837440.0
accuracy for training set for epoch 5720 is  :  0.41447368264198303
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 5720 is  :  0.2486666738986969 and loss is 1766705332224.0
accuracy for training set for epoch 5725 is  :  0.3881579041481018
predictions:  [[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
accuracy for validation set for epoch 5725 is  :  0.24400000274181366 and loss is 1771667062784.0
accuracy for training set for epoch 5730 is  :  0.46052631735801697
predictions:  [[0. 0. 0.

accuracy for validation set for epoch 5865 is  :  0.2473333328962326 and loss is 1724617850880.0
accuracy for training set for epoch 5870 is  :  0.4736842215061188
predictions:  [[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
accuracy for validation set for epoch 5870 is  :  0.24799999594688416 and loss is 1722503790592.0
accuracy for training set for epoch 5875 is  :  0.3684210479259491
predictions:  [[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
accuracy for validation set for epoch 5875 is  :  0.24199999868869781 and loss is 1726519705600.0
accuracy for training set for epoch 5880 is  :  0.3552631437778473
predictions:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
accuracy for validation set for epoch 5880 is  :  0.2446666657924652 and loss is 1717072429056.0
accuracy for training set for epoch 5885 is  :  0.33552631735801697
predictions:  [[0. 0. 0. 1

In [ ]:
meta_dir = weights+'.meta'



In [ ]:
tf.reset_default_graph()
graph = tf.get_default_graph()
saver = tf.train.import_meta_graph(meta_dir)

val_dataset = load_dataset(img_dir= val_dir,frequency_dir=frequency_val_dir,minibatch_size=1500,image_size=INPUT_SIZE,grayscale=GRAYSCALE,num_parallel_calls=NUM_PARRALLEL_THREADS,is_frequency=IS_FREQUENCY)

val_iterator = tf.data.Iterator.from_structure(val_dataset.output_types,val_dataset.output_shapes)
val_init_op = val_iterator.make_initializer(val_dataset,name='val_init_op')
 

with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:
    
    
    print('validation dataset...')
    sess.run(tf.global_variables_initializer())
    saver.restore(sess, tf.train.latest_checkpoint(weight_dir))
   
    iterator_handle = graph.get_tensor_by_name('data_handle:0')
    val_handle = sess.run(val_iterator.string_handle())
    

    
    sess.run(val_init_op,feed_dict={iterator_handle:val_handle})

    accuracy_op = graph.get_tensor_by_name('accuracy/accuracy_operation:0')
   
    while True:
        try:
            val_accuracy = sess.run([accuracy_op],feed_dict={iterator_handle:val_handle})

        except tf.errors.OutOfRangeError:
            print("accuracy for validation set :  {0}".format(val_accuracy))
            break



In [ ]:
tf.reset_default_graph()
graph = tf.get_default_graph()
saver = tf.train.import_meta_graph(meta_dir)

test_dataset = load_dataset(img_dir= test_dir,frequency_dir=frequency_test_dir,minibatch_size=1500,image_size=INPUT_SIZE,grayscale=GRAYSCALE,num_parallel_calls=NUM_PARRALLEL_THREADS,is_frequency=IS_FREQUENCY)

test_iterator = tf.data.Iterator.from_structure(test_dataset.output_types,test_dataset.output_shapes)
test_init_op = test_iterator.make_initializer(test_dataset,name='test_init_op')


with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:
    
    
    print('testing dataset...')
    sess.run(tf.global_variables_initializer())
    saver.restore(sess, tf.train.latest_checkpoint(weight_dir))
   # val_op = graph.get_operation_by_name("iterators/val_init_op")
    iterator_handle = graph.get_tensor_by_name('data_handle:0')
    test_handle = sess.run(test_iterator.string_handle())

    
    sess.run(test_init_op,feed_dict={iterator_handle:test_handle})

    accuracy_op = graph.get_tensor_by_name('accuracy/accuracy_operation:0')
   
    while True:
        try:
            test_accuracy = sess.run([accuracy_op],feed_dict={iterator_handle:test_handle})

        except tf.errors.OutOfRangeError:
            print("accuracy for testing set :  {0}".format(test_accuracy))
            break

